language: node_js

node_js:
  - "stable"
  - "lts/*"

branches:
  only:
    - dev

cache:
  directories:
  - node_modules

before_script:
  - "npm i -g gatsby-cli"
  - "yarn"

script:
  - gatsby build

  deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: master